### ISSUE TITLE
Ad-Request comments not appearing

### ISSUE THREAD

**Issue by sdwolfe32** [Glyciant/PurplePlus#56]
I'm seeing an issue where I have an ad-request that appears to have a single comment already on it, however I cannot view it once I click into the ad-request. See below screenshots
[Proof of a Comment](https://image.prntscr.com/image/gWLx_9EsSbGP19xl6K0AfQ.png)
[No Comment](https://image.prntscr.com/image/LzKs4JgWTKuEFL291Gn2Cg.png)
My Twitch account name (and likely Purple+ name) is Vizicore.

**Comment by Glyciant** [comment]
That'll because it's private for subreddit moderators. I'll change it so it doesn't count those for the people who can't see them. Thanks! 🙂
