### ISSUE TITLE
Earning twoos with removal of communities 

### ISSUE THREAD

**Issue by tehbasshunter** [Glyciant/PurplePlus#65]
With the removal of communities I'd like to think that it's not possible to earn twoos unless this has been fix prior to/since tthe change.

**Comment by Glyciant** [comment]
There are other ways, although they're not currently as prominent. Don't worry though, we're aware of this and are actively looking at other ways to earn. However, these may not be within Purple+, so I'm going to mark this as `Won't Act Upon`.
